# Generated by Django 2.1.4 on 2019-02-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvFile', models.FileField(upload_to='Document/csv', verbose_name='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('opening_text', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('subregion', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('article_content', models.TextField(blank=True)),
                ('english_translation', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True)),
                ('concept_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
