# Generated by Django 2.1.4 on 2019-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sentiment_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
