# Generated by Django 2.1.4 on 2019-02-11 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_inputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
